### Tests
@url = http://localhost:8000

### Get Spotify Metadata
POST {{url}}/v1/spotify/meta
Content-Type: application/json

{
    "url": "https://open.spotify.com/track/4uLU6hMCjMI75M1A2tKUQC"
}

### Search Youtube
POST {{url}}/v1/youtube/search
Content-Type: application/json

{
    "query": "Never Gonna Give You Up Rick Astley"
}

### Download Youtube
POST {{url}}/v1/youtube/download
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
}

### Full Convert Flow
POST {{url}}/v1/convert
Content-Type: application/json

{
    "url": "https://open.spotify.com/track/4uLU6hMCjMI75M1A2tKUQC"
}
